Zero-to-Heroes/firestone

core/src/js/components/settings/general/settings-general-launch.component.ts, core/src/js/models/preferences.ts, core/src/js/services/notifications.service.ts
https://github.com/Zero-to-Heroes/firestone/pull/26 with one additional commit to use the new variable throughout the code.
Since the PR was made on a fork I could not author it, so I have created a new one, but the commits are still attributed to you :)
=> Improve wording of the Hide All Notifications settings (and change its behavior internally to match)

core/src/js/services/mercenaries/mercenaries-utils.ts
Add boots of hast to speed buff modifier
=> Add boots of hast to speed buff modifier

core/src/css/component/collection/full-card.component.scss, core/src/js/components/collection/full-card.component.ts
• Add new types of card sounds: "Wow", "Picked", "Happy Holidays"
• Add recognition of alternate spellings of some sound filenames
• Remove capitalization of sound filenames because it looks pretty bad in some Non-English languages
• Remove "[x]" from cards flavor text found in Kazakus (BoM Kurtrus' story) and Lady Anacondra (BoM Guff's story)
• Fix multi-class cards bug
• Add check for undefined card class
• Add card rarity display
=> Full-card.component improvements

core/src/js/components/collection/card-history-item.component.ts, core/src/js/components/tooltip/card-tooltip.component.ts
=> Fix golden cards tooltip for both card history and best opened packs

core/src/js/components/battlegrounds/battles/bgs-simulator-minion-selection.component.ts
=> Fix minions tooltip in simulator

core/src/js/components/battlegrounds/desktop/categories/hero-details/bgs-hero-detailed-stats.component.ts, core/src/js/components/battlegrounds/post-match/stat-cell.component.ts, core/src/js/components/decktracker/main/deck-matchup-info.component.ts, core/src/js/components/decktracker/main/deck-winrate-matrix.component.ts, core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stat.component.ts
=> LOC: Externalize strings

core/src/css/component/overlays/duels-ooc/duels-deck-widget.component.scss, core/src/js/components/overlays/duels-ooc/duels-deck-widget.component.ts
=> Add null check for MMR value & center align Your last deck label

core/src/js/components/arena/desktop/arena-run.component.ts
=> Fix arena replay not displaying opponent name

core/src/js/components/collection/set-stats.component.ts
=> Fix golden duplicate dust tooltip

core/src/js/components/collection/full-card-back.component.ts
=> Add card back description sanitizing

core/src/js/services/collection/card-notifications.service.ts
Change new cards notification text, now it become acceptable for non-English languages: "New golden card: {{cardName}}"
=> Change new cards notification text: "New golden card: {{cardName}}"

core/src/js/components/decktracker/main/decktracker-rating-graph.component.ts
=> Change rating graph labels format

core/src/js/components/mercenaries/desktop/mercenaries-meta-hero-stat.component.ts
=> Change mercs tooltip: "Name (role)"

core/src/js/components/settings/decktracker/settings-decktracker-your-deck.ts
=> Fix abyssal-curse-tooltip

core/src/js/components/collection/full-card.component.ts
=> FEATURE: display golden card in collection if user has one

core/src/css/component/collection/hero-portraits.component.scss
**Before:**
**After:**
**Before:**
**After:**
=> Improve layout of hero portraits component

core/src/js/components/collection/full-card.component.ts
=> Improve card sounds determination

core/src/js/components/battlegrounds/battles/bgs-battle.component.ts
=> Hide reposition-button-tooltip-finalresult after the end of reposition

core/src/css/component/duels/desktop/duels-buckets.component.scss
=> Improve display of bucket names

core/src/js/components/battlegrounds/desktop/categories/hero-details/bgs-warband-stats-for-hero.component.ts, core/src/js/components/battlegrounds/desktop/categories/hero-details/bgs-winrate-stats-for-hero.component.ts
=> Localize Community and You labels in BG graphs legends

core/src/css/component/duels/desktop/duels-buckets.component.scss, core/src/js/components/duels/desktop/duels-buckets.component.ts
=> Add buckets search empty state to buckets view

core/src/js/components/decktracker/decktracker.component.ts
=> Add replays recap to ladder-ranking view

core/src/js/components/mercenaries/desktop/mercenaries-desktop.component.ts
=> Add search bar to mercenaries-meta-hero-stats

core/src/css/component/duels/desktop/deckbuilder/duels-deckbuilder-cards.component.scss, core/src/js/components/duels/desktop/deckbuilder/duels-deckbuilder-cards.component.ts
=> Add cards search empty state to duels deckbuilder

core/src/css/component/decktracker/main/deckbuilder/constructed-deckbuilder-cards.component.scss, core/src/js/components/decktracker/main/deckbuilder/constructed-deckbuilder-cards.component.ts
=> Add cards search empty state to constructed deckbuilder

core/src/css/component/decktracker/main/deck-winrate-matrix.component.scss, core/src/css/component/decktracker/main/decktracker-deck-recap.component.scss, core/src/css/component/decktracker/main/decktracker-stats-for-replays.component.scss, core/src/css/component/duels/desktop/duels-desktop.component.scss, core/src/css/component/duels/desktop/secondary/duels-deck-stats.component.scss
=> Center align multiple labels that span two lines in non-English languages or at small window size

core/src/css/component/mercenaries/desktop/mercenaries-meta-hero-stats.component.scss, core/src/js/components/mercenaries/desktop/mercenaries-meta-hero-stats.component.ts, core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stats.component.ts
=> Add search empty state for mercs

core/src/css/component/collection/full-card.component.scss, core/src/js/components/collection/full-card.component.ts
=> Display number of diamond copies in full-card-component

core/src/js/components/collection/full-card.component.ts
=> Add check for undefined rarity (for coins)

core/src/css/component/decktracker/main/deckbuilder/constructed-deckbuilder-breadcrumbs.component.scss, core/src/css/component/duels/desktop/deckbuilder/duels-deckbuilder-breadcrumbs.component.scss
=> Fix import icon when zoom level is increased

core/src/js/services/mercenaries/mercenaries-utils.ts
* Add short names for the following mercenaries: Brann, Lokholar, Valeera, Trigore, Balinda, Reno, Sylvanas, Baine, Elise, Rogers, Athissa, Cho, Azshara. 
* Localize short name of the Lich King.
**Before:**
**After:**
=> Add some merc short names & localize Lich King

core/src/js/services/hs-utils.ts
=> Change class colors to more HS-like

core/src/js/components/collection/full-card.component.ts
* Change class display of Neutral cards from "All classes" to "Neutral".
* Add null check for class value (for mercs)
**Before:**
**After:**
=> Change class display in full card component

core/src/js/components/collection/filters/card-class-filter.component.ts
=> Added the Neutral option to card class filter

core/src/css/component/duels/desktop/duels-hero-stat-vignette.component.scss, core/src/css/component/duels/desktop/duels-hero-stats.component.scss
=> Improve layout of duels-hero-stat-vignette

core/src/css/component/battlegrounds/graph-with-comparison.component.scss, core/src/js/components/battlegrounds/desktop/categories/hero-details/bgs-warband-stats-for-hero.component.ts, core/src/js/components/battlegrounds/desktop/categories/hero-details/bgs-winrate-stats-for-hero.component.ts, core/src/js/components/battlegrounds/graph-with-comparison-new.component.ts, core/src/js/components/battlegrounds/post-match/bgs-chart-warband-stats.component.ts, core/src/js/components/battlegrounds/post-match/bgs-winrate-chart.component.ts
=> Localize strings in graph-with-comporison

core/src/css/component/battlegrounds/graph-with-comparison.component.scss, core/src/js/components/battlegrounds/graph-with-comparison-new.component.ts
=> Improve graph-with-comparison tooltip layout

core/src/css/component/battlegrounds/battles/bgs-simulator-minion-selection.component.scss, core/src/js/components/battlegrounds/battles/bgs-simulator-minion-selection.component.ts
=> Improve minion selection window layout

core/src/js/components/collection/set.component.ts, core/src/js/components/main-window/global-header.component.ts, core/src/js/services/mainwindow/store/processors/collection/select-collection-set-processor.ts
=> Localize set names in set header and set component

core/src/js/services/mainwindow/store/processors/achievements/select-achievement-category-processor.ts
=> Change achievements categories separator

core/src/css/component/replays/replay-info/replay-info-mercenaries.component.scss, core/src/js/components/replays/replay-info/replay-info-mercenaries.component.ts
**Before:**
**After:**
**Before:**
**After:**
=> Improve mercs replay info

core/src/css/component/replays/replays-list.component.scss
=> Fix Use class icons toggle overlap with replays list

core/src/js/components/replays/replay-info/replay-info-duels.component.ts, core/src/js/components/replays/replay-info/replay-info-generic.component.ts, core/src/js/components/replays/replay-info/replay-info-ranked.component.ts
=> Add opponent hero name tooltip in replays

core/src/css/component/decktracker/main/filters/_decktracker-filters.component.scss, core/src/css/component/decktracker/main/filters/constructed-my-decks-search.component.scss, core/src/js/components/decktracker/main/filters/constructed-my-decks-search.component.ts
=> Fix search decks component for display on decktracker-ladder-stats

core/src/css/component/decktracker/main/decktracker-ladder-stats-overview.component.scss, core/src/js/components/decktracker/main/decktracker-ladder-stats-overview.component.ts
=> Enabled pie chart legend in decktracker-ladder-stats

core/src/css/component/decktracker/main/decktracker-replays-recap.component.scss
=> Center align "Last X replays" label

core/src/css/component/battlegrounds/in-game/bgs-hero-face-offs.component.scss, core/src/css/component/battlegrounds/post-match/bgs-chart-hp.component.scss, core/src/css/component/battlegrounds/post-match/bgs-post-match-stats-recap.component.scss, core/src/css/component/settings/preference-toggle.component.scss
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> Minor battlegrounds window improvements

core/src/css/component/decktracker/main/deck-winrate-matrix.component.scss, core/src/css/component/decktracker/main/decktracker-deck-details.component.scss
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> Improve layout of decktracker-deck-details

README.md
=> Update Overwolf button in README

core/src/js/components/collection/pack-stats.component.ts
=> Improve packs sorting

core/src/css/component/filter-dropdown-multiselect.component.scss, core/src/css/component/settings/checkbox.component.scss, core/src/js/components/filter-dropdown-multiselect.component.ts, core/src/js/components/settings/checkbox.component.ts
**Before:**
**After:**
**Before:**
**After:**
=> Move option image in filter multiselect dropdown

core/src/js/components/mercenaries/overlay/teams/mercenaries-team-ability.component.ts
Change merc ability cooldown tooltip to "On cooldown for X turns"
=> Change merc ability cooldown tooltip

core/src/css/component/duels/desktop/duels-personal-deck-vignette.component.scss
=> Expand duel deck name container

core/src/js/components/battlegrounds/post-match/bgs-post-match-stats-recap.component.ts
=> Add default value if Battles going first is NaN

core/src/css/component/achievements/achievements-filter.component.scss, core/src/css/component/duels/desktop/secondary/duels-treasure-search.component.scss, core/src/css/component/mercenaries/desktop/secondary/mercenaries-hero-search.component.scss
=> Fix narrow inputs in search components

core/src/js/services/mercenaries/mercenaries-utils.ts
Add short names for the following mercenaries: Vanndar, Leeroy, Guff, Kurtrus, Tyrande, Edwin, Anacondra, Vashj, Mukla, Krush.
=> Add some merc short names

core/src/css/component/battlegrounds/hero-selection/bgs-hero-selection-tooltip.component.scss
=> Fix border of bgs hero selection tooltip

core/src/js/services/mercenaries/highlights/mercenaries-synergies-highlight-processor.ts
* Add highlight for League Recruitment Flyer and Can't Touch This
* Fix highlight for Murloc Infestation
* Update Horde and Alliance race lists
=> Improve synergies highlight

core/src/css/component/overlays/turntimer/turn-timer-widget.component.scss
=> Turn timer improvements

core/src/js/components/duels/desktop/filters/duels-dust-filter-dropdown.component.ts, core/src/js/models/duels/duels-types.ts
=> Make duels dust filter options multiples of cards cost

core/src/js/components/collection/full-card.component.ts, core/src/js/services/mercenaries/mercenaries-utils.ts
=> Add faction and race info to full-card component (faction only for mercs)

core/src/js/components/mercenaries/overlay/teams/mercenaries-team-ability.component.ts, core/src/js/components/mercenaries/overlay/teams/mercenaries-team-list.component.ts, core/src/js/components/mercenaries/overlay/teams/mercenaries-team-mercenary.component.ts, core/src/js/components/mercenaries/overlay/teams/mercenaries-team-root..component.ts
=> Mercs: Disable opponent ability highlighting

core/src/js/components/settings/mercenaries/settings-mercenaries-quests.component.ts
=> Use short names in settings-mercenaries-quests

core/src/css/component/battlegrounds/battles/bgs-simulator-hero-power-selection.component.scss, core/src/css/component/battlegrounds/battles/bgs-simulator-hero-selection.component.scss, core/src/css/component/battlegrounds/battles/bgs-simulator-minion-selection.component.scss, core/src/css/component/battlegrounds/battles/bgs-simulator-quest-reward-selection.component.scss
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Center align minion attributes**
**Before:**
**After:**
=> Change text color of search components placeholder in simulator

core/src/css/component/duels/desktop/filters/duels-hero-filter-dropdown.component.scss, core/src/css/component/filter-dropdown-multiselect.component.scss
**! Can be merged only with PR https://github.com/Zero-to-Heroes/firestone/pull/230 !**
**Before:**
**After:**
**Before:**
**After:**
=> Disable option text wrapping in filter multiselect dropdown

core/src/css/component/streams/desktop/live-stream-info-elements-sizes.scss, core/src/css/component/streams/desktop/live-stream-info.component.scss, core/src/js/components/streams/desktop/live-stream-info.component.ts
=> Improve live-stream-info component

core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stat.component.ts, core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stats.component.ts
Also hide speed value for Discover abilities
=> Display related cards on Progress tab

core/src/css/component/mercenaries/overlay/action-queue/mercenaries-action-queue.component.scss, core/src/css/component/mercenaries/overlay/action-queue/mercenaries-action.component.scss
=> Improve action queue

core/src/assets/svg/TwitchGlitchPurple.svg
=> Fix Twitch logo svg file

core/src/css/component/collection/card-history.component.scss
=> Right align "Show only new cards" toggle label

core/src/js/services/mercenaries/highlights/mercenaries-synergies-highlight-processor.ts
=> Add highlight for abilities with combo effect

core/src/css/component/mercenaries/overlay/action-queue/mercenaries-action.component.scss
=> Fix merc action name overflow

README.md
current, the branch redirects to 'edit', which blocks it for anyone without direct write access. Feel free to close PR if that's the wanted outcome.
=> chore: update link on readme
