Zero-to-Heroes/firestone

core/package-lock.json, core/package.json, core/src/js/services/collection/pack-monitor.service.ts
I noticed `ts-keycode-enum` was only used in 1 place and the same thing can be achieved with `@angular/cdk` which is used elsewhere. I didn't test this yet, because I wasn't sure how to create that scenario. The IDE shows the same value, so it seems pretty straight forward.
This is very minor, so you may not even want to bother with it, but I just wanted to mention it
=> Remove ts-keycode-enum dependency

core/src/css/component/notifications/notifications.component.scss
The plus symbol for dust recap amount should not be added via the css file, but should be contained in the source line. I think this is bad programming practice. This change is also required for non-English languages.
=> Dust recap

core/src/js/components/collection/pack-stats.component.ts
Standard and Wild packs moved to the main sets list. So for now it's true, that special packs is unbuyable ones.
=> Moving packs

core/src/css/component/filter-dropdown-multiselect.component.scss
• Fix a bug where when you hover over the control buttons in duels hero selection dropdown, labels become not visible because of the same background and font color.
• Enlarge Clear and Reset buttons in multiselect dropdown. In Russian, inscriptions require a little bit more space. Probably in some non-English languages too.
=> Filter-dropdown-multiselect improvements

core/src/css/component/settings/general/settings-general.component.scss, core/src/js/components/settings/decktracker/settings-decktracker-global.ts, core/src/js/components/settings/general/settings-general-launch.component.ts, core/src/js/components/settings/general/settings-general-third-party.component.ts
• In some non-English languages, some settings labels span two lines and all elements don't fit on the page, so it should be scrollable.
• Fix bug with reset positions button tooltip
• Fix d0nkey instructions page link
=> Settings improvements

core/src/js/components/collection/full-card.component.ts
Most multiclass cards don't have a class specified as Neutral, so we should determine multiclass cards by the length of card.classes (e.g. Raise Dead).
=> Fix determination of multiclass cards

core/src/js/components/mercenaries/overlay/teams/mercenaries-team-ability.component.ts
[Tested locally]
• There is already a tooltip on the element as a whole (line: 16), duplicate tooltip on the equipment icon is not needed.
=> Remove duplicate equipment tooltip in mercs team widget

core/src/js/components/decktracker/overlay/decktracker-winrate-recap.component.ts
There is an obvious mistake here: tooltip string is used instead of recap text
=> Fix winrate vs class recap in decktracker

core/src/css/component/decktracker/import-deckstring.component.scss
In some cases, the import button may shrink to an indistinguishable size, so it should have a fixed width.
=> Set fixed width for deck import icon in decktracker

core/src/css/component/decktracker/copy-deckstring.component.scss, core/src/js/components/decktracker/copy-deckstring.component.ts
Make the "Copy deck code" text itself also clickable. The CSS rule also move to match.
=> Increase Copy deck code button size

core/src/js/components/collection/set.component.ts, core/src/js/models/collection/reference-set.ts, core/src/js/services/collection/sets.ref.ts
Tag all adventures as mini-sets so that "Next guaranteed" doesn't display for them in the collection
=> Tag all adventures as mini-sets

core/src/js/components/duels/desktop/secondary/duels-tier.component.ts
Move tooltip closer to the tier title.
**Before:**
**After:**
=> Change treasures tier list tooltip position

core/src/css/component/notifications/notifications.component.scss, core/src/js/services/collection/card-notifications.service.ts
Change layout of receiving cards notification. Now it looks better when card name spans two lines. Also make clickable the entire text area of notification.
**Before:**
**After:**
=> Card notification improvements

core/src/js/components/duels/desktop/duels-hero-stat-vignette.component.ts
Remove duplicate class names from tooltip for neutral heroes in Duels. Also change tooltip text, so now it's "Hero (Class)"
=> Fix duels heroes tooltip

core/src/css/component/battlegrounds/bgs-hero-portrait.component.scss, core/src/css/component/battlegrounds/desktop/categories/battlegrounds-stats-hero-vignette.component.scss, core/src/css/component/decktracker/main/decktracker-deck-summary.component.scss, core/src/css/component/duels/desktop/duels-personal-deck-vignette.component.scss, core/src/css/component/duels/desktop/secondary/duels-deck-stats.component.scss
The most noticeable changes are:
• Morgl in Constructed
• Brann and Reno in Duels
• King Lich in Battlegrounds
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> Improve crop of images for hero portraits

core/src/css/component/mercenaries/desktop/mercenaries-personal-hero-stat.component.scss, core/src/css/component/mercenaries/desktop/mercenaries-personal-team-summary.component.scss, core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stat.component.ts
• **Improve crop of images for mercs portraits in personal team summary**
**Before:**
**After:**
• **Improve crop of equipment icons in personal hero stats**
Before:
After:
• **Improve layout of where to farm coins tooltip**
Before:
After:
=> Minor mercs improvements

core/src/js/components/collection/cards.component.ts
Since filters affect search results, they should be displayed, otherwise user will be confused.
**Before:**
**After:**
=> Display filters in cards search results

core/src/css/component/battlegrounds/bgs-player-capsule.component.scss, core/src/css/component/battlegrounds/in-game/bgs-opponent-overview-big.component.scss, core/src/js/components/battlegrounds/overlay/bgs-overlay-hero-overview.component.ts
• **Externalized string "Latest upgrade"**
**Before:**
**After:**
• **Improved layout of tavern upgrades section of bgs-opponent-overview**
• **Fixed last opponent icon overlap with hero frame**
**After:**
=> Minor bgs-opponent-overview improvements

core/src/css/component/overlays/duels-ooc/duels-hero-power-info.component.scss, core/src/css/component/overlays/duels-ooc/duels-signature-treasure-info.component.scss
Add line break for "Win distribution" (for non-English languages). Align Winrate and Popularity labels to the right.  Remove duplicate properties.
**Before:**
**After:**
=> Improve layout of hero-power-info and signature-treasure-info

core/src/js/components/mercenaries/desktop/mercenaries-personal-hero-stat.component.ts
=> Fix 0 speed abilities in mercs personal hero stats

core/src/css/component/achievements/achievement-progress-bar.component.scss, core/src/js/components/achievements/achievement-progress-bar.component.ts
The error occurred after some use cases of the application (e.g. going to view any hero in collection and back to achievements). I feel like I'm fixing symptoms of some bigger problem here: progress bar shouldn't be displayed differently depending on the use case.
**Before:**
**After:**
=> Fix achievements progress bar sometimes not displayed

core/src/css/component/decktracker/main/decktracker-deck-summary.component.scss, core/src/css/component/mercenaries/desktop/mercenaries-personal-team-summary.component.scss, core/src/js/components/decktracker/main/decktracker-deck-summary.component.ts, core/src/js/components/mercenaries/desktop/mercenaries-personal-team-summary.component.ts
Before:
After:
I understand that it may not be very correct to use regular expressions to truncate the string, but it can't be done through toLocaleDateString.
=> Improved deck summary component layout

core/src/css/component/battlegrounds/bgs-board.component.scss, core/src/css/component/battlegrounds/in-game/bgs-next-opponent-overview.component.scss, core/src/css/component/battlegrounds/in-game/bgs-opponent-overview-big.component.scss, core/src/css/component/battlegrounds/in-game/bgs-opponent-overview.component.scss, core/src/css/component/battlegrounds/in-game/bgs-quest-rewards.component.scss, core/src/css/component/battlegrounds/in-game/bgs-triples.component.scss, core/src/css/component/battlegrounds/overlay/bgs-overlay-hero-overview.component.scss, core/src/js/components/battlegrounds/bgs-board.component.ts, core/src/js/components/battlegrounds/in-game/bgs-opponent-overview-big.component.ts, core/src/js/components/battlegrounds/in-game/bgs-opponent-overview.component.ts
**What was done:**
* All empty states are center aligned
* Changed empty state for tavern upgrades: removed Last upgrades/Tavern upgrades label
* Quest rewards centered
* Improved view display when zoom level is increased.
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
=> Improve layout of bgs-next-opponent-overview

core/src/css/component/replays/replay-info/replay-info.component.scss
In some non-English languages, localized time string doesn't fit in the field.
=> Increase replay time field size

core/src/css/component/battlegrounds/graph-with-comparison.component.scss, core/src/css/component/collection/pack-stats.component.scss, core/src/css/component/common/chart/pie-chart.component.scss, core/src/css/component/duels/desktop/filters/_duels-filters.component.scss
**Before:**
**After:**
**Before:**
**After:**
**Before:**
**After:**
**Display border between two sections in graph with comparison tooltip only if both exist.**
**Before:**
**After:**
=> Minor visual improvements

core/src/css/component/mercenaries/overlay/teams/mercenaries-team-mercenary.component.scss, core/src/css/component/mercenaries/overlay/teams/mercenaries-team-root.component.scss, core/src/js/components/mercenaries/overlay/teams/mercenaries-team-root..component.ts
**What was done:**
* Footer:
* Simplify layout
* Tasks and roles chart buttons change size depending on content
* Remove weird onclick effect
* Round corners
* Add background for merc name container (for hover effect)
**Before:**
**After:**
**Before:**
**After:**
=> Mercs team widget layout improvements

core/src/css/component/decktracker/overlay/decktracker-title-bar.component.scss, core/src/js/components/decktracker/overlay/decktracker-cards-recap.component.ts
* Now cards in deck and cards in hand tooltips are displayed on entire block, not just on icon.
* Visual improvements
**Before:**
**After:**
=> Decktracker improvements

core/src/js/services/mercenaries/mercenaries-utils.ts
=> Hide speed value for abilities with Discover and Battlecry effects

core/src/js/components/collection/full-card.component.ts
Apart from that:
* Fix problem of incorrect sounds categorization of many portraits (most of the sounds were in Other)
* Fix [problem](https://stackoverflow.com/questions/20463349/why-the-results-from-running-exactly-the-same-regular-expression-twice-are-diffe) of double-check regular expressions - solved by replacing `test` with `match`
* Add Disabled category - for Priest portraits
**Before:**
**After:**
**Before:**
**After:**
**After:**
=> Simplify and improve categorization and determination of card sounds

core/src/js/components/mercenaries/overlay/teams/mercenaries-team-mercenary.component.ts
Along with this commit, you should upload this image to the server at https://static.zerotoheroes.com/hearthstone/asset/firestone/mercenaries_icon_golden_neutral.png
=> Add display of neutral icon in mercs team widget

core/src/js/components/mercenaries/overlay/teams/mercenaries-team-mercenary.component.ts
=> Fix display of neutral icon in mercs team widget

core/src/js/services/mercenaries/parser/mercenaries-ability-revealed-parser.ts, core/src/js/services/mercenaries/parser/mercenaries-hero-revealed-parser.ts
Fix incorrect cooldown of Garona's and Eudora's Starts off cooldown abilities and Long'xin's, Holmes', Bwonsamdi's, Khadgar's, Natalie's abilities when they have equipment interacting with cooldown. 
Initially, cooldown of abilities should be 0, if it actually differs from zero, then the MERCENARIES_COOLDOWN_UPDATED event occurs.
**Before:**
**After:**
=> Fix incorrect cooldown of some mercs abilities

core/src/js/components/mercenaries/overlay/teams/mercenaries-out-of-combat-player-team.component.ts
=> Fix incorrect equipment tier in out of combat team widget

core/src/js/services/mercenaries/mercenaries-store.service.ts, core/src/js/services/mercenaries/parser/mercenaries-ability-queued-parser.ts
We can't tell from game events which ability is selected when Discover ability is queued, so we shouldn't display such abilities at all.
=> Don't display Discover abilities in action queue

core/src/css/component/battlegrounds/bgs-player-capsule.component.scss, core/src/css/component/replays/replay-info/replay-info-battlegrounds.component.scss
=> Improve display of match-details component when zoomed level increased

core/src/js/components/decktracker/main/deckbuilder/constructed-deckbuilder-class.component.ts, core/src/js/models/collection/filter-types.ts, core/src/js/services/hs-utils.ts
You should also upload class icon at
https://static.zerotoheroes.com/hearthstone/asset/firestone/images/deck/classes/deathknight.png
=> Add base support for Death Knight class

libs/stats/common/src/lib/components/replay-info-generic-2.component.ts
Fixes runtime displays formatted at an hour+ not 0 padding.
1:6 hours should actually be 1:06 hours, 3:9 hours should actually be 3:09 hours, etc.
Does not include the 0 place if hours = 0 so we don't get clunky 07:53 minutes and just 7:53 minutes instead.
Previous:
Current:
=> Fix 0-pad for minutes place if totalRunTime >= 1h

libs/game-state/src/lib/counters/impl/naga-giant.ts
Overrides existing formatting for Naga Giant to present the current cost.
We discussed formatting it like abyssal curses, but I think it's better to format it that way it's consistent with Ceaseless (AKA Ceaseless now costs X, and only showing X)
Before:
After:
Happy to adjust as you see fit.
=> Fix naga giant label formatting

libs/game-state/src/lib/related-cards/dynamic-pools.ts, libs/game-state/src/lib/related-cards/related-cards.ts, libs/legacy/feature-shell/src/lib/js/components/overlays/opponenthand/opponent-card-info-id.component.ts, libs/legacy/feature-shell/src/lib/js/components/overlays/opponenthand/opponent-card-info.component.ts, libs/legacy/feature-shell/src/lib/js/components/overlays/opponenthand/opponent-card-infos.component.ts, libs/legacy/feature-shell/src/lib/js/components/overlays/opponenthand/opponent-hand-overlay.component.ts, libs/legacy/feature-shell/src/lib/js/services/decktracker/card-highlight/cards-highlight-common.service.ts, libs/legacy/feature-shell/src/lib/js/services/decktracker/event-parser/custom-effects-parser.ts
Original Discord Thread: https://discord.com/channels/187101197767933952/1372915546479136788
TBD: Screenshots for Validation(s)
I've also added in a way to implement GameState which can be helpful for some cards (Emerald Portals, Corpse Farm, etc)
And I've added in some utility functions to simplify the logic / code written in the dynamic-pools.ts file.
I made updates and added dynamic card pools to the following checked items:
- Botface (which I believe i implemented properly, but doesnt look like it's properly working (tagging on the backend, perhaps for Minis?)
=> Update dynamic pools for s56 arena
